"""empty message

Revision ID: 1e460dc9e6f8
Revises: 978a841713a8
Create Date: 2019-07-15 17:03:45.898582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e460dc9e6f8'
down_revision = '978a841713a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('updated_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'updated_by')
    # ### end Alembic commands ###
