"""empty message

Revision ID: 978a841713a8
Revises: bdf77d3b9488
Create Date: 2019-07-02 16:08:13.706536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '978a841713a8'
down_revision = 'bdf77d3b9488'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'comment', ['id'])
    op.create_unique_constraint(None, 'project', ['id'])
    op.add_column('request', sa.Column('project_desc', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'request', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'request', type_='unique')
    op.drop_column('request', 'project_desc')
    op.drop_constraint(None, 'project', type_='unique')
    op.drop_constraint(None, 'comment', type_='unique')
    # ### end Alembic commands ###
